# NUMPY

In [1]:
import numpy

In [2]:
a=numpy.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
a.shape

(5,)

In [5]:
import numpy as np

In [8]:
b=np.array([22,45,32,82,555,66])

In [9]:
b

array([ 22,  45,  32,  82, 555,  66])

In [11]:
b.shape

(6,)

These were 1D Array creation

2D Array creation

In [12]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [13]:
a.shape

(2, 2)

In [15]:
a=np.array([[44,22],[43,54]])
a

array([[44, 22],
       [43, 54]])

In [16]:
a.shape

(2, 2)

In [18]:
c=np.array([[1,2],[3,4],[5,6]])
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
x=np.array([[61,21,89],[32,42,56]])
x

array([[61, 21, 89],
       [32, 42, 56]])

In [20]:
x.shape

(2, 3)

In [22]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
d.shape

(3, 3)

In [26]:
e=np.array([[4,5,7,8],[3,4,8,9],[8,7,6,5]])
e           

array([[4, 5, 7, 8],
       [3, 4, 8, 9],
       [8, 7, 6, 5]])

In [27]:
e.shape

(3, 4)